### ISSUE TITLE
npm start errors

### ISSUE THREAD

**Issue by remainstheday** [yiminghe/learning-react#1]
I followed the "Run" steps line for line but keep getting a `'node --harmony server'` error. 
![screen shot 2015-02-28 at 1 06 33 am](https://cloud.githubusercontent.com/assets/4063510/6425454/6c637d5e-bee6-11e4-8f63-aaa83cb4faff.png)

**Comment by yiminghe** [comment]
please install node 0.12

**Comment by carlesso** [comment]
I'm havin the same issue using node `v0.12.6` and node `v2.12.1` but with Exit status 1

![screenshot_2015-07-14_18-24-42](https://cloud.githubusercontent.com/assets/207895/8678603/a7ab05fa-2a55-11e5-8ab5-6972c0b7da3a.png)

Here my [npm-debug.log](https://gist.github.com/carlesso/e6b8b830d005e2a358da)

**Comment by yiminghe** [comment]
try rm node_modules and npm install again
