### ISSUE TITLE
npm run build Error...

### ISSUE THREAD

**Issue by timothykrichards** [yiminghe/learning-react#2]
I get the following error when I run "npm run build";

> learning-react@1.0.0 build C:\Dev\learning-react
> rm -rf build && webpack -d

'rm' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\Users\Tim\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "build"
npm ERR! node v0.10.35
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE
npm ERR! learning-react@1.0.0 build: `rm -rf build && webpack -d`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the learning-react@1.0.0 build script 'rm -rf build && webpack -d'.
npm ERR! This is most likely a problem with the learning-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf build && webpack -d
npm ERR! You can get their info via:
npm ERR!     npm owner ls learning-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Dev\learning-react\npm-debug.log

**Comment by yiminghe** [comment]
sorry, this does not work on windows, suggest using mac or linux (or on virtual machine), this also only runs on node 0.12
