### ISSUE TITLE
react-router的ie8下不兼容

### ISSUE THREAD

**Issue by hufeng** [yiminghe/learning-react#4]
您好yiminghe，我们使用了react-router0.13.3发现打了es5-shim和es5-sham后，在ie8里面还是不兼容，老是会抛ERR_ACCESSORS_NOT_SUPPORTED 异常，请问您是怎么解决的呢？

**Comment by yiminghe** [comment]
嗯，已经解决了 https://github.com/rackt/react-router/issues/1475
